# Notes
This is just a raw dumping ground for bits and pieces I found useful. There is zero logic to the layout of this page
## Calculate the distance between 2 cogs
In this example, we have two cogs, one with 16 teeth and one with 14 teeth with a module of 1.38. The formula is

Distance = (Module x (Teeth 1 + Teeth 2)) / 2
=(1.38 x (16 + 14)) / 2
= 20.7mm

Shoulder cogs will be 15mm horizontally apart and 14.26mm vertically apart

See [https://www.youtube.com/watch?v=IhcLSx2ppUY](https://www.youtube.com/watch?v=IhcLSx2ppUY)

## How to space shafts a set distance apart
See [https://forum.freecad.org/viewtopic.php?t=53574](https://forum.freecad.org/viewtopic.php?t=53574)

## Adjusted Dimensions for 3D Printing
**Standard meshing to use** - Based on an exported standard mesh with 0.1mm surface deviation, 10-degree angular deviation, and relative surface deviation

Holes for 10mm bearing = 5.2r = 10 dia hole when printed

Holes to accept servo cogs (2.4r) = 4.8 dia hole when printed. Is a tight fit which is needed

Dia of shaft passing through bearing = 5.8 Dia = 6 m dia for inside bearing

Holes for servo self-tapping screws 1.4 Dia

Holes to passthrough self-tapping screws 2.0 Dia
